WEBHOOK_PASSPHRASE = None

DISCORD_LOGS_URL = None
DISCORD_ERR_URL = None
DISCORD_AVATAR_URL = None
DISCORD_STUDY_URL = None
DISCORD_STUDY_AVATAR_URL = None

LEVERAGE_MYBYBITACCOUNT = None
RISK_MYBYBITACCOUNT = None
API_KEY_MYBYBITACCOUNT = None
API_SECRET_MYBYBITACCOUNT = None

LEVERAGE_STRATEGY_TWO = None
RISK_STRATEGY_TWO = None
API_KEY_STRATEGY_TWO = None
API_SECRET_STRATEGY_TWO = None
